### ISSUE TITLE
How to update recursive submodules?

### ISSUE THREAD

**Issue by feltus** [feltus/OSG-MCF10-MOD#1]
Hi Mats.  I am starting to develop this workflow (slowly).  One issue is to recursively clone the model code. I have tried lots of things like:

[ffeltus@login03 test]$ git submodule update https://github.com/birtwistle/Mechanistic_Pan-Cancer_Model.git --init
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

How to do this?

Thanks!

Alex

**Comment by rynge** [comment]
First, to do the recursive checkout:

git clone --recursive git@github.com:feltus/OSG-MCF10-MOD.git

Once you have the checkout and you want to pull all the updates from Git:

git pull --recurse-submodules

Does that answer the question?

**Comment by feltus** [comment]
Thanks Mats. After I update, it says the recursive repo is up to date but it is not (see below).  I think it is pointing to an old branch?  

https://github.com/birtwistlelab/Mechanistic_Pan-Cancer_Model/tree/2b41da0be3c39f8abc06b1481b9fe4db4004bb6f

instead of 

https://github.com/birtwistlelab/Mechanistic_Pan-Cancer_Model

[ffeltus@login03 mcf10a]$ git clone https://github.com/feltus/OSG-MCF10-MOD.git --recurse-submodules
Cloning into 'OSG-MCF10-MOD'...
remote: Counting objects: 45, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 45 (delta 17), reused 24 (delta 5), pack-reused 0
Unpacking objects: 100% (45/45), done.
Submodule 'Mechanistic_Pan-Cancer_Model' (https://github.com/birtwistlelab/Mechanistic_Pan-Cancer_Model.git) registered for path 'Mechanistic_Pan-Cancer_Model'
Cloning into 'Mechanistic_Pan-Cancer_Model'...
remote: Counting objects: 170, done.
remote: Total 170 (delta 0), reused 0 (delta 0), pack-reused 170
Receiving objects: 100% (170/170), 1.20 MiB | 0 bytes/s, done.
Resolving deltas: 100% (84/84), done.
Submodule path 'Mechanistic_Pan-Cancer_Model': checked out '2b41da0be3c39f8abc06b1481b9fe4db4004bb6f'

[ffeltus@login03 OSG-MCF10-MOD]$ git pull --recurse-submodules
Fetching submodule Mechanistic_Pan-Cancer_Model
Already up-to-date.

**Comment by rynge** [comment]
I think we had not added the submodule correctly. I readded it with:

git submodule add --force -b master https://github.com/birtwistlelab/Mechanistic_Pan-Cancer_Model.git

It now says it tracks "master" if you cd into Mechanistic_Pan-Cancer_Model and run "git status"

You might have to do a new checkout to get this change.

**Comment by feltus** [comment]
2300 karma points.  I'm using bitcoin karma points now so I am not certain of their power. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Mats Rynge <notifications@github.com> Date: 7/22/18  10:03 PM  (GMT-05:00) To: feltus/OSG-MCF10-MOD <OSG-MCF10-MOD@noreply.github.com> Cc: Alex Feltus <alex.feltus@gmail.com>, Author <author@noreply.github.com> Subject: Re: [feltus/OSG-MCF10-MOD] How to update recursive submodules? (#1) 
I think we had not added the submodule correctly. I readded it with:
git submodule add --force -b master https://github.com/birtwistlelab/Mechanistic_Pan-Cancer_Model.git
It now says it tracks "master" if you cd into Mechanistic_Pan-Cancer_Model and run "git status"
You might have to do a new checkout to get this change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/feltus/OSG-MCF10-MOD","title":"feltus/OSG-MCF10-MOD","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/feltus/OSG-MCF10-MOD"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rynge in #1: I think we had not added the submodule correctly. I readded it with:\r\n\r\ngit submodule add --force -b master https://github.com/birtwistlelab/Mechanistic_Pan-Cancer_Model.git\r\n\r\nIt now says it tracks \"master\" if you cd into Mechanistic_Pan-Cancer_Model and run \"git status\"\r\n\r\nYou might have to do a new checkout to get this change."}],"action":{"name":"View Issue","url":"https://github.com/feltus/OSG-MCF10-MOD/issues/1#issuecomment-406918016"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/feltus/OSG-MCF10-MOD/issues/1#issuecomment-406918016",
"url": "https://github.com/feltus/OSG-MCF10-MOD/issues/1#issuecomment-406918016",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [feltus/OSG-MCF10-MOD] How to update recursive submodules? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Mats Rynge**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@rynge",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"feltus/OSG-MCF10-MOD\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"feltus/OSG-MCF10-MOD\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/feltus/OSG-MCF10-MOD/issues/1#issuecomment-406918016"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 358812367\n}"
}
],
"themeColor": "26292E"
}
]
