### ISSUE TITLE
Executables in tools dir

### ISSUE THREAD

**Issue by feltus** [feltus/OSG-MCF10-MOD#2]
Hi Mats.  I m learning how this works but I am confused about how the dax generator knows the executable name.  I made a python script called job-wrapper in the tools dir.  How does the dax generator know this is the file to execute as it appears it is finding it in a list (below).  Thanks!

# Add executables to the DAX-level replica catalog
for exe_name in os.listdir('./tools/'):
    exe = Executable(name=exe_name, arch='x86_64', installed=False)
    exe.addPFN(PFN('file://' + base_dir + '/tools/' + exe_name, 'local'))
    dax.addExecutable(exe)

**Comment by rynge** [comment]
That section just register the executables and their location. Later when you create the job, it is `name` attribute which picks which of those executable to use:

job = Job(name='job-wrapper')

**Comment by feltus** [comment]
Yes! I understand!


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Mats Rynge <notifications@github.com> Date: 7/25/18  1:37 PM  (GMT-05:00) To: feltus/OSG-MCF10-MOD <OSG-MCF10-MOD@noreply.github.com> Cc: Alex Feltus <alex.feltus@gmail.com>, Author <author@noreply.github.com> Subject: Re: [feltus/OSG-MCF10-MOD] Executables in tools dir (#2) 
That section just register the executables and their location. Later when you create the job, it is name attribute which picks which of those executable to use:
job = Job(name='job-wrapper')
