### ISSUE TITLE
Jobs failing

### ISSUE THREAD

**Issue by feltus** [feltus/OSG-MCF10-MOD#3]
Hi Mats.  I still can't get this to run.  I think I modified everything so I can run python scripts (e.g. trail.py) inside the recursive model directory (see readme for this repo).  The jobs launch and then fail.    Below is the workflow.  I seem to start working on this and then days go by but I will run serious jobs once I know the flaw. Alex

----------------------------------------------------
The following workflow issued an event: at_end

  /local-scratch/ffeltus/workflows/osg-mcf10-mod-1534186124/osg-mcf10-mod-1534186124

Below is output from pegasus-status:

    ID S IN_STATE PRI JOB                                                                                                                    
686096 R    39:38   0 osg-mcf10-mod-0 ( /local-scratch/ffeltus/workflows/osg-mcf10-mod-1534186124/osg-mcf10-mod-1534186124 ) [pegasus-dagman]
Summary: 1 Condor job total (R:1)

UNREADY   READY     PRE  QUEUED    POST SUCCESS FAILURE %DONE
      4       0       0       0       0       2      10  12.5
Summary: 1 DAG total (Failure:1)

**Comment by rynge** [comment]
I fixed one mismatch between the submit and job-wrapper scripts. However, the job wrapper is trying to invoke trail.py which does not exist. Did the subrepo change maybe?
